name: gptsimi

recipe: lamp

config:
  php: '7.3'
  webroot: .
  database: mysql:8.0

services:
  appserver:
    ssl: true
    sslExpose: true
    
  database:
    portforward: 3306

proxy:
  appserver:
    - gptsimi.lndo.site